version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: cripto
      POSTGRES_PASSWORD: cripto123
      POSTGRES_DB: criptoactivos
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://cripto:cripto123@db:5432/criptoactivos
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: always
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db_data:
